### ISSUE TITLE
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).

### ISSUE THREAD

**Issue by aovoc** [tengshaofeng/ResidualAttentionNetwork-pytorch#2]
I ran your code and meet the error as below:

`ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "train_pre.py", line 52, in <module>
    for i, (images, labels) in enumerate(train_loader):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 275, in __next__
    idx, batch = self._get_batch()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 254, in _get_batch
    return self.data_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 343, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 175, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 50) is killed by signal: Bus error.`

The run environment is python 3.5, tensorflow 1.0.1 and pythorch 0.3.1. I have search for the solutions.  And  I think this maybe cause by version confilicts. 

Can you tell us the run environment, and any other suggestion? thx

**Comment by aovoc** [comment]
The problem has been solved. It is caused by insufficient shm because I run it in a docker environment. when I rerun the docker with setting  `--ipc=host` the problem doesn't appear again. 

ps: I changed the pytorch version from 0.3.1 to 0.2.0_3.
